### ISSUE TITLE
Ask for sudo user password on deploy:setup

### ISSUE THREAD

**Issue by sharshenov** [kalys/capistrano-nginx-unicorn#1]
`deploy:setup` performs actions that require root privileges.
We can specify `sudo_user` option in our `config/deploy.rb` file. And it would be nice if `cap deploy:setup` can ask password of `sudo_user` to perform root actions.

**Comment by kalys** [comment]
![untitle](https://f.cloud.github.com/assets/155511/2413789/47d92632-aae2-11e3-8181-8ae49e1c59f0.JPG)
