### ISSUE TITLE
Delete request - 405 Not Allowed

### ISSUE THREAD

**Issue by petermumford** [kalys/capistrano-nginx-unicorn#15]
I'm using the nginx conf and when I try to delete a record via a DELETE request method it returns with a '405 Not Allowed' instead of a UJS response.

Below is the code I'm using within my view. This will then return some JS. It works fine on my development machine but not on my production server.

`link_to("Delete", image, method: :delete, remote: true, data:{confirm: "Are you Sure?"})`

I've googled around and everything I've found doesn't work, for example : http://leandroardissone.com/post/19690882654/nginx-405-not-allowed and http://andre.arko.net/2011/06/30/rails-page-caching-nginx-and-restful-apis/

I'm at a bit of a lost as I'm not sure what to do, would you?

**Comment by petermumford** [comment]
Finally found the cause of the problem. 

This line: `location ~ ^/(assets|images|javascripts|stylesheets|swfs|system)/ {` I changed to `location ^~ /(assets|images|javascripts|stylesheets|swfs|system)/`

You'll see that I changed the `~^` and this made everything work as normal. 

Hopefully this was just a typo? Let me know.

**Comment by kalys** [comment]
Thank you for your report. Fixed. https://github.com/kalys/capistrano-nginx-unicorn/commit/87c09e344126dc39dcb4cec78170872337e2d848
