### ISSUE TITLE
unicorn_config needs to be on the server ?

### ISSUE THREAD

**Issue by mabid** [kalys/capistrano-nginx-unicorn#5]
I don't know if this is a real issue or I am getting something wrong, From my understanding the first thing to deploy to a fresh server is

``` ruby
cap deploy:setup
```

which will setup unicorn and will need the unicorn_config to be on the server to run the following ?

``` ruby
template "unicorn.rb.erb", unicorn_config
```

Does that mean I am supposed to manually put that file somewhere on the server ? I cannot have the file in my app under version control because when deploy:setup runs there is no code yet on the server ?

To resolve this issue, I had to add a task

``` ruby
 namespace :unicorn do
     task :copy_config do
        put File.read(unicorn_config_local_path), "/tmp/unicorn_config.rb"
        run "#{sudo} mv /tmp/unicorn_config.rb #{shared_path}/config/unicorn_config.rb"
      end
 end
```

Which essentially just copies my local unicorn config to the server before setting up unicorn.

Am I totally misunderstanding something here ?

**Comment by kalys** [comment]
Consider the following task https://github.com/kalys/capistrano-nginx-unicorn/blob/b389a007f5a8918ff04cf8a2abb3a6d656ca7a99/lib/capistrano/nginx_unicorn/tasks.rb#L53.

As you can see at line 55 `template` method applies configuration variables to erb template then saves file as `unicorn_config` path. By default `unicorn_config` has value `"#{shared_path}/config/unicorn.rb"`.

ERB file is here https://github.com/kalys/capistrano-nginx-unicorn/blob/b389a007f5a8918ff04cf8a2abb3a6d656ca7a99/lib/generators/capistrano/nginx_unicorn/templates/unicorn.rb.erb.

You can generate it by running `rails generate capistrano:nginx_unicorn:config`.
